# Generated by Django 3.2.9 on 2021-12-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('no_of_members', models.IntegerField()),
                ('team_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='teamlist',
        ),
    ]
